# Generated by Django 5.0.2 on 2024-02-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_value', models.CharField(max_length=255)),
                ('page_image', models.ImageField(upload_to='barcodes/')),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfscanner.pdfdocument')),
            ],
        ),
    ]
